<div id="filters">
			<p><label for="language">Idioma:</label>
				<select name="hl" id="language">
				<option value="">---‬</option> 
				<option value="af">afrikaans - ‪Afrikaans‬</option> 
				<option value="de">alemão - ‪Deutsch‬</option> 
				<option value="am">amárico - ‪አማርኛ‬</option> 
				<option value="ar">árabe - ‫العربية‬</option> 
				<option value="eu">basco - ‪euskara‬</option> 
				<option value="bn">bengali - ‪বাংলা‬</option> 
				<option value="bg">búlgaro - ‪български‬</option> 
				<option value="kn">canarim - ‪ಕನ್ನಡ‬</option> 
				<option value="ca">catalão - ‪català‬</option> 
				<option value="cs">checo - ‪čeština‬</option> 
				<option value="zh-CN">chinês (han simplificado) - ‪简体中文‬</option> 
				<option value="zh-TW">chinês (han tradicional) - ‪繁體中文‬</option> 
				<option value="zh-HK">chinês (Hong Kong) - ‪中文（香港）‬</option> 
				<option value="ko">coreano - ‪한국어‬</option> 
				<option value="hr">croata - ‪hrvatski‬</option> 
				<option value="da">dinamarquês - ‪dansk‬</option> 
				<option value="sk">eslovaco - ‪slovenčina‬</option> 
				<option value="sl">esloveno - ‪slovenščina‬</option> 
				<option value="es-419">espanhol (América Latina) - ‪español (Latinoamérica)‬</option> 
				<option value="es">espanhol (Espanha) - ‪español (España)‬</option> 
				<option value="et">estónio - ‪eesti‬</option> 
				<option value="fil">filipino - ‪Filipino‬</option> 
				<option value="fi">finlandês - ‪suomi‬</option> 
				<option value="fr-CA">francês (Canadá) - ‪français (Canada)‬</option> 
				<option value="fr">francês (França) - ‪français (France)‬</option> 
				<option value="gl">galego</option> 
				<option value="el">grego - ‪Ελληνικά‬</option> 
				<option value="gu">guzerate - ‪ગુજરાતી‬</option> 
				<option value="iw">hebraico - ‫עברית‬</option> 
				<option value="hi">hindi - ‪हिन्दी‬</option> 
				<option value="nl">holandês - ‪Nederlands‬</option> 
				<option value="hu">húngaro - ‪magyar‬</option> 
				<option value="id">indonésio - ‪Bahasa Indonesia‬</option> 
				<option value="en">inglês (Estados Unidos) - ‪English (United States)‬</option> 
				<option value="en-GB">inglês (Reino Unido) - ‪English (United Kingdom)‬</option> 
				<option value="is">islandês - ‪íslenska‬</option> 
				<option value="it">italiano</option> 
				<option value="ja">japonês - ‪日本語‬</option> 
				<option value="lv">letão - ‪latviešu‬</option> 
				<option value="lt">lituano - ‪lietuvių‬</option> 
				<option value="ml">malaiala - ‪മലയാളം‬</option> 
				<option value="ms">malaio - ‪Bahasa Melayu‬</option> 
				<option value="mr">marata - ‪मराठी‬</option> 
				<option value="no">norueguês - ‪norsk‬</option> 
				<option value="or">oriya - ‪ଓଡ଼ିଆ‬</option> 
				<option value="fa">persa - ‫فارسی‬</option> 
				<option value="pl">polaco - ‪polski‬</option> 
				<option value="pt-BR">português (Brasil)</option> 
				<option value="pt">português (Portugal)</option> 
				<option value="ro">romeno - ‪română‬</option> 
				<option value="ru">russo - ‪русский‬</option> 
				<option value="sr">sérvio - ‪Српски‬</option> 
				<option value="sw">suaili - ‪Kiswahili‬</option> 
				<option value="sv">sueco - ‪svenska‬</option> 
				<option value="th">tailandês - ‪ไทย‬</option> 
				<option value="ta">tâmil - ‪தமிழ்‬</option> 
				<option value="te">telugu - ‪తెలుగు‬</option> 
				<option value="tr">turco - ‪Türkçe‬</option> 
				<option value="uk">ucraniano - ‪українська‬</option> 
				<option value="ur">urdu - ‫اردو‬</option> 
				<option value="vi">vietnamita - ‪Tiếng Việt‬</option> 
				<option value="zu">zulu - ‪isiZulu‬</option></select>
			</p>
</div>